@RandomizedWitchNobeta.WebSettings_HostAddress = http://localhost:5115

GET {{RandomizedWitchNobeta.WebSettings_HostAddress}}/todos/
Accept: application/json

###

GET {{RandomizedWitchNobeta.WebSettings_HostAddress}}/todos/1
Accept: application/json

###
